name: Deploy to CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuración de AWS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Instalar dependencias y hacer el build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Subir el build a S3
      - name: Sync build files to S3
        run: |
          aws s3 sync ./dist/ s3://mymodal --delete

      # Invalidar caché de CloudFront
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
